select e.ENAME,d.DNAME, d.DLOC 
FROM EMPLOYEE e, DEPT d
WHERE e.DEPTNO=d.DEPTNO;

SELECT e.ENAME, e.EMPNO
FROM EMPLOYEE e
LEFT JOIN ASSIGNED_TO a ON e.EMPNO=a.EMPNO
WHERE a.PNO IS NULL;

SELECT p.PNO, p.PNAME, COUNT(*) AS HEADCOUNT
FROM PROJECT p
LEFT JOIN ASSIGNED_TO a ON p.PNO=a.PNO
GROUP BY p.PNAME
ORDER BY HEADCOUNT DESC;

SELECT e.EMPNO, e.ENAME, SUM(i.INCENTIVE_AMOUNT) AS TOTAL_INCENTIVES
FROM EMPLOYEE e, INCENTIVES i
WHERE e.EMPNO=i.EMPNO
GROUP BY e.EMPNO, e.ENAME;

SELECT e.EMPNO, e.ENAME, a.JOB_ROLE
FROM EMPLOYEE e, ASSIGNED_TO a, PROJECT p
WHERE e.EMPNO=a.EMPNO AND a.PNO=p.PNO AND p.PNAME='ALPHA PROJECT';

SELECT e.EMPNO, e.ENAME, a.JOB_ROLE
FROM EMPLOYEE e, ASSIGNED_TO a, PROJECT p
WHERE e.EMPNO=a.EMPNO AND a.PNO=p.PNO AND p.PNAME='PAYROLL SYSTEM';

SELECT d.DEPTNO, d.DNAME, d.DLOC
FROM DEPT d, EMPLOYEE e
WHERE d.DEPTNO=e.DEPTNO AND e.EMPNO=NULL;

SELECT m.EMPNO AS MANNAGER_NO, m.ENAME AS MANAGER_NAME, COUNT(e.EMPNO) AS REPORT_COUNT
FROM EMPLOYEE e, EMPLOYEE m
WHERE e.MGR_NO=m.EMPNO
GROUP BY m.EMPNO;

SELECT e.EMPNO, e.ENAME, COUNT(DISTINCT PNO) AS PROJECT_COUNT
FROM EMPLOYEE e, ASSIGNED_TO a
WHERE a.EMPNO=e.EMPNO
GROUP BY e.EMPNO
HAVING COUNT(DISTINCT a.PNO)>1;